// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1;

#nullable disable

namespace Project1.Migrations
{
    [DbContext(typeof(FishDbContext))]
    [Migration("20230913172502_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project1.Models.DailyFish", b =>
                {
                    b.Property<int>("DailyFishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dailyfish_id");

                    b.Property<string>("DailyFishImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DailyFishImage");

                    b.Property<string>("DailyFishName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DailyFishName");

                    b.HasKey("DailyFishId");

                    b.ToTable("DailyFishs");
                });
#pragma warning restore 612, 618
        }
    }
}
